all: vector map multimap

vector: vector.cpp
	g++ -pedantic -Wall -g -o vector vector.cpp

map: map.cpp
	g++ -Wall -g -o map map.cpp

multimap: multimap.cpp
	g++ -Wall -g -o multimap multimap.cpp

clean:
	rm -f vector map multimap
