# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1390946574);
user_pref("app.update.lastUpdateTime.background-update-timer", 1390946454);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1390946694);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1390953414);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1390946334);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.lastDir", "/user/student/xjin/Project02");
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.slowStartup.averageTime", 1988);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20131214222425");
user_pref("browser.startup.homepage_override.mstone", "24.2.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1377795489185");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1390951385401");
user_pref("datareporting.policy.firstRunTime", "1377709089184");
user_pref("datareporting.sessions.current.activeTicks", 196);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 971);
user_pref("datareporting.sessions.current.main", 24);
user_pref("datareporting.sessions.current.sessionRestored", 1716);
user_pref("datareporting.sessions.current.startTime", "1390951321890");
user_pref("datareporting.sessions.current.totalTime", 4420);
user_pref("datareporting.sessions.currentIndex", 13);
user_pref("datareporting.sessions.previous.12", "{\"s\":1390946091650,\"a\":191,\"t\":4270,\"c\":true,\"m\":24,\"fp\":3746,\"sr\":4199}");
user_pref("datareporting.sessions.prunedIndex", 11);
user_pref("devtools.toolbox.selectedTool", "inspector");
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountTotal", 13);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.2.0");
user_pref("extensions.hotfix.lastVersion", "20130826.01");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox-24.2.0/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1387083744000,\"rdfTime\":1387083702000}}}]");
user_pref("extensions.lastAppVersion", "24.2.0");
user_pref("extensions.lastPlatformVersion", "24.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20131214222425");
user_pref("gecko.mstone", "24.2.0");
user_pref("idle.lastDailyNotification", 1390947240);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.database", "{\"files\":[{\"fingerprint\":\"2b24e27c5e52bdbef45711706a125b1\",\"exists\":true,\"page\":2,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":592}]}");
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1390947244);
user_pref("places.history.expiration.transient_current_max_pages", 99774);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("spellchecker.dictionary", "en-US");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1390947244);
user_pref("toolkit.startup.last_success", 1390951321);
user_pref("toolkit.telemetry.previousBuildID", "20131214222425");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1393538103);
user_pref("urlclassifier.updatecachemax", 1024);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
