calc: calc.o dstack.o
	g++ -Wall -pedantic -g -o calc calc.o dstack.o

dstack.o: dstack.h dstack.cpp
	g++ -Wall -pedantic -g -c dstack.cpp

calc.o: dstack.h calc.cpp
	g++ -Wall -pedantic -g -c calc.cpp

clean:
	rm -f calculator calc.exe calc.o dstack.o
