all:
	g++ -Wall -pedantic -o infinite_50000 infinite_50000.cpp
	g++ -Wall -pedantic -o infinite infinite.cpp
	g++ -Wall -pedantic -o run_time_stack_memory run_time_stack_memory.cpp
	g++ -Wall -pedantic -o heap heap.cpp
	g++ -Wall -pedantic -o collision collision.cpp

clean:
	rm -f infinite infinite_5000 run_time_stack_memory heap collision
